<div class="admin__field-note">
    <div class="feed-status-item">
        The <a href="https://experienceleague.adobe.com/en/docs/commerce/saas-data-export/data-synchronization" target="_blank">data synchronization</a> status includes the following information for each feed:
        <br/>

        <ul>
            <li><strong>Feed Name:</strong> The name of the feed indexer responsible for synchronizing a specific entity or its part, for example product or product price.</li>
            <li><strong>Source Records:</strong> Number of Commerce records that require synchronization.
                The number may be larger than the number of records displayed in the Admin Grid of the entity source, as each feed item belongs to a specific scope, such as a Store View Code.
            </li>
            <li><strong>Successfully Sent Records:</strong> Number of records successfully transmitted to Commerce SaaS for further processing.
                If errors occurred during the synchronization process, this number may be smaller than the number of source records.
                For more details, click the link in the "Action" column.
            </li>
            <li><strong>Failed Records:</strong> Number of records that failed to be sent to Commerce SaaS.
                For more details, click the link in the "Action" column.
            </li>
        </ul>
    </div>
</div>
